version: "3.3"
services:
  neo4j:
    build:
      context: ./build/neo4j/
      args:
        neo4jLogging: std
    hostname: shell
    environment:
      - EXTENDED_CONF=yes
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_directories_import=/mount
      # For remote aliases
      - NEO4J_dbms_security_keystore_path=/var/lib/neo4j/conf/secrets
      - NEO4J_dbms_security_keystore_password=foobar
      - NEO4J_dbms_security_key_name=secrets
      - NEO4J_db_transaction_timeout=10s
      # Plugins
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
    volumes:
      - ./mount:/mount:ro
