# This layer adds elasticsearch + kibana, and sets up neo4j to send all logs there
# Kibana will be available at http://localhost:5601/

version: "3.3"
services:
  neo4j:
    build:
      args:
        neo4jLogging: elk
        
  elk:
    # Might require on host machine > sudo sysctl -w vm.max_map_count=262144
    build:
      context: ./build/elk
    ports:
      - "5601:5601"
      - "9200:9200"
    environment:
      - LOGSTASH_START=0
      - ES_HEAP_SIZE=4g